<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title>v8: v8::TryCatch Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css">
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.5.8 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
      <li><a href="examples.html"><span>Examples</span></a></li>
    </ul>
  </div>
  <div class="tabs">
    <ul>
      <li><a href="annotated.html"><span>Class&nbsp;List</span></a></li>
      <li><a href="hierarchy.html"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
  <div class="navpath"><a class="el" href="namespacev8.html">v8</a>::<a class="el" href="classv8_1_1_try_catch.html">TryCatch</a>
  </div>
</div>
<div class="contents">
<h1>v8::TryCatch Class Reference</h1><!-- doxytag: class="v8::TryCatch" --><code>#include &lt;<a class="el" href="v8_8h-source.html">v8.h</a>&gt;</code>
<p>

<p>
<a href="classv8_1_1_try_catch-members.html">List of all members.</a><table border="0" cellpadding="0" cellspacing="0">
<tr><td></td></tr>
<tr><td colspan="2"><br><h2>Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classv8_1_1_try_catch.html#dc9b1b11e73b0325df727914c348053d">TryCatch</a> ()</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classv8_1_1_try_catch.html#2c9ad4b40d17dd31c6dd020736b30679">~TryCatch</a> ()</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">bool&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classv8_1_1_try_catch.html#48f704fbf2b82564b5d2a4ff596e4137">HasCaught</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">bool&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classv8_1_1_try_catch.html#2ec467d4653d26c064d749cab98791cb">CanContinue</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="el" href="classv8_1_1_handle.html">Handle</a>&lt; <a class="el" href="classv8_1_1_value.html">Value</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classv8_1_1_try_catch.html#4a7506617800bbc49c3c08bbfefb9c2d">ReThrow</a> ()</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="el" href="classv8_1_1_local.html">Local</a>&lt; <a class="el" href="classv8_1_1_value.html">Value</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classv8_1_1_try_catch.html#99c425f29b3355b4294cbe762377f99b">Exception</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="el" href="classv8_1_1_local.html">Local</a>&lt; <a class="el" href="classv8_1_1_value.html">Value</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classv8_1_1_try_catch.html#1ee3e6ee74a4fc50185443ccdc4d3ae7">StackTrace</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="el" href="classv8_1_1_local.html">Local</a>&lt; <a class="el" href="classv8_1_1_message.html">v8::Message</a> &gt;&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classv8_1_1_try_catch.html#2811e500fbb906ee505895a3d94fc66f">Message</a> () const </td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">void&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classv8_1_1_try_catch.html#3aae8acab4c99b374b7d782763d4c8e1">Reset</a> ()</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">void&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classv8_1_1_try_catch.html#032cd889d76bd596e2616df11ced8682">SetVerbose</a> (bool value)</td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top">void&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el" href="classv8_1_1_try_catch.html#541b8fa6951bd5a439692c22d5c7b73c">SetCaptureMessage</a> (bool value)</td></tr>

<tr><td colspan="2"><br><h2>Friends</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="anchor" name="a7f9ec8d1a5e5ffb7bf3981ccf851c82"></a><!-- doxytag: member="v8::TryCatch::v8::internal::Top" ref="a7f9ec8d1a5e5ffb7bf3981ccf851c82" args="" -->
class&nbsp;</td><td class="memItemRight" valign="bottom"><b>v8::internal::Top</b></td></tr>

</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
An external exception handler. <hr><h2>Constructor &amp; Destructor Documentation</h2>
<a class="anchor" name="dc9b1b11e73b0325df727914c348053d"></a><!-- doxytag: member="v8::TryCatch::TryCatch" ref="dc9b1b11e73b0325df727914c348053d" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">v8::TryCatch::TryCatch           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Creates a new try/catch block and registers it with <a class="el" href="namespacev8.html">v8</a>. 
</div>
</div><p>
<a class="anchor" name="2c9ad4b40d17dd31c6dd020736b30679"></a><!-- doxytag: member="v8::TryCatch::~TryCatch" ref="2c9ad4b40d17dd31c6dd020736b30679" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">v8::TryCatch::~TryCatch           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Unregisters and deletes this try/catch block. 
</div>
</div><p>
<hr><h2>Member Function Documentation</h2>
<a class="anchor" name="2ec467d4653d26c064d749cab98791cb"></a><!-- doxytag: member="v8::TryCatch::CanContinue" ref="2ec467d4653d26c064d749cab98791cb" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool v8::TryCatch::CanContinue           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td> const</td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
For certain types of exceptions, it makes no sense to continue execution.<p>
Currently, the only type of exception that can be caught by a <a class="el" href="classv8_1_1_try_catch.html">TryCatch</a> handler and for which it does not make sense to continue is termination exception. Such exceptions are thrown when the TerminateExecution methods are called to terminate a long-running script.<p>
If CanContinue returns false, the correct action is to perform any C++ cleanup needed and then return. 
</div>
</div><p>
<a class="anchor" name="99c425f29b3355b4294cbe762377f99b"></a><!-- doxytag: member="v8::TryCatch::Exception" ref="99c425f29b3355b4294cbe762377f99b" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classv8_1_1_local.html">Local</a>&lt;<a class="el" href="classv8_1_1_value.html">Value</a>&gt; v8::TryCatch::Exception           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td> const</td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns the exception caught by this try/catch block. If no exception has been caught an empty handle is returned.<p>
The returned handle is valid until this <a class="el" href="classv8_1_1_try_catch.html">TryCatch</a> block has been destroyed. 
</div>
</div><p>
<a class="anchor" name="48f704fbf2b82564b5d2a4ff596e4137"></a><!-- doxytag: member="v8::TryCatch::HasCaught" ref="48f704fbf2b82564b5d2a4ff596e4137" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool v8::TryCatch::HasCaught           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td> const</td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns true if an exception has been caught by this try/catch block. 
</div>
</div><p>
<a class="anchor" name="2811e500fbb906ee505895a3d94fc66f"></a><!-- doxytag: member="v8::TryCatch::Message" ref="2811e500fbb906ee505895a3d94fc66f" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classv8_1_1_local.html">Local</a>&lt;<a class="el" href="classv8_1_1_message.html">v8::Message</a>&gt; v8::TryCatch::Message           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td> const</td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns the message associated with this exception. If there is no message associated an empty handle is returned.<p>
The returned handle is valid until this <a class="el" href="classv8_1_1_try_catch.html">TryCatch</a> block has been destroyed. 
</div>
</div><p>
<a class="anchor" name="3aae8acab4c99b374b7d782763d4c8e1"></a><!-- doxytag: member="v8::TryCatch::Reset" ref="3aae8acab4c99b374b7d782763d4c8e1" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void v8::TryCatch::Reset           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Clears any exceptions that may have been caught by this try/catch block. After this method has been called, <a class="el" href="classv8_1_1_try_catch.html#48f704fbf2b82564b5d2a4ff596e4137">HasCaught()</a> will return false.<p>
It is not necessary to clear a try/catch block before using it again; if another exception is thrown the previously caught exception will just be overwritten. However, it is often a good idea since it makes it easier to determine which operation threw a given exception. 
</div>
</div><p>
<a class="anchor" name="4a7506617800bbc49c3c08bbfefb9c2d"></a><!-- doxytag: member="v8::TryCatch::ReThrow" ref="4a7506617800bbc49c3c08bbfefb9c2d" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classv8_1_1_handle.html">Handle</a>&lt;<a class="el" href="classv8_1_1_value.html">Value</a>&gt; v8::TryCatch::ReThrow           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Throws the exception caught by this <a class="el" href="classv8_1_1_try_catch.html">TryCatch</a> in a way that avoids it being caught again by this same <a class="el" href="classv8_1_1_try_catch.html">TryCatch</a>. As with ThrowException it is illegal to execute any JavaScript operations after calling ReThrow; the caller must return immediately to where the exception is caught. 
</div>
</div><p>
<a class="anchor" name="541b8fa6951bd5a439692c22d5c7b73c"></a><!-- doxytag: member="v8::TryCatch::SetCaptureMessage" ref="541b8fa6951bd5a439692c22d5c7b73c" args="(bool value)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void v8::TryCatch::SetCaptureMessage           </td>
          <td>(</td>
          <td class="paramtype">bool&nbsp;</td>
          <td class="paramname"> <em>value</em>          </td>
          <td>&nbsp;)&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Set whether or not this <a class="el" href="classv8_1_1_try_catch.html">TryCatch</a> should capture a <a class="el" href="classv8_1_1_message.html">Message</a> object which holds source information about where the exception occurred. True by default. 
</div>
</div><p>
<a class="anchor" name="032cd889d76bd596e2616df11ced8682"></a><!-- doxytag: member="v8::TryCatch::SetVerbose" ref="032cd889d76bd596e2616df11ced8682" args="(bool value)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void v8::TryCatch::SetVerbose           </td>
          <td>(</td>
          <td class="paramtype">bool&nbsp;</td>
          <td class="paramname"> <em>value</em>          </td>
          <td>&nbsp;)&nbsp;</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Set verbosity of the external exception handler.<p>
By default, exceptions that are caught by an external exception handler are not reported. Call SetVerbose with true on an external exception handler to have exceptions caught by the handler reported as if they were not caught. 
</div>
</div><p>
<a class="anchor" name="1ee3e6ee74a4fc50185443ccdc4d3ae7"></a><!-- doxytag: member="v8::TryCatch::StackTrace" ref="1ee3e6ee74a4fc50185443ccdc4d3ae7" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classv8_1_1_local.html">Local</a>&lt;<a class="el" href="classv8_1_1_value.html">Value</a>&gt; v8::TryCatch::StackTrace           </td>
          <td>(</td>
          <td class="paramname">          </td>
          <td>&nbsp;)&nbsp;</td>
          <td> const</td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>
Returns the .stack property of the thrown object. If no .stack property is present an empty handle is returned. 
</div>
</div><p>
<hr>The documentation for this class was generated from the following file:<ul>
<li>/home/riku/cornerstone/JS/v8-r4957/include/<a class="el" href="v8_8h-source.html">v8.h</a></ul>
</div>
<hr size="1"><address style="text-align: right;"><small>Generated on Mon Jun 28 13:06:50 2010 for v8 by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border="0"></a> 1.5.8 </small></address>
</body>
</html>
